"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "ka" | "ru";
export type Theme = "dark" | "light" | "contrast";

type Dictionary = Record<string, string>;

const translations: Record<Language, Dictionary> = {
  en: {
    analyze: "Analyze",
    batch: "Batch",
    compare: "Compare",
    formats: "Formats",
    engine: "Engine",
    privacy: "Privacy",
    analysisModes: "Analysis modes",
    productInformation: "Product information",
    localFirst: "Local-first",
    home: "DolosMeta home",
    skipToMain: "Skip to main content",
    menu: "Menu",
    mobileNavigation: "Mobile navigation",
    footerNote: "Metadata is editable. Treat findings as observations, not proof.",
    handled: "How files are handled",
    language: "Language",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    contrast: "High contrast",
    localFileIntelligence: "Local file intelligence",
    entranceTitle: "See what your files reveal.",
    entranceCopy: "DolosMeta identifies file structure, surfaces embedded metadata, traces location and creation signals, and highlights privacy exposure without sending files to third parties.",
    capabilities: "DolosMeta capabilities",
    identify: "Identify",
    inspect: "Inspect",
    clean: "Clean",
    preparing: "Preparing your private workspace",
    skipIntro: "Skip intro",
    singleFile: "Single file",
    chooseWorkflow: "Choose analysis workflow",
    universalIntelligence: "Universal file intelligence",
    heroCopy: "Inspect hidden metadata, timestamps, geolocation, device information, document properties, and file structure in one private workspace.",
    dropFile: "Drop a file here",
    clickChoose: "or click to choose a file",
    retention: "Files stay on this DolosMeta instance and are removed automatically.",
    nativeParsing: "Native parsing",
    noExifTool: "No ExifTool dependency",
    privateByDesign: "Private by design",
    noExternalUploads: "No external analysis uploads",
    evidenceAware: "Evidence-aware",
    observationsNotVerdicts: "Observations, not verdicts",
    analysisInterrupted: "Analysis interrupted",
    couldNotInspect: "We could not inspect this file.",
    tryAgain: "Try again",
    chooseAnother: "Choose another file",
    analysisUnavailable: "Analysis unavailable",
    savedAnalysis: "Saved analysis",
    retrieveAnalysis: "Retrieving the analysis result from this DolosMeta session.",
    analysisInProgress: "Analysis in progress",
    serverInspecting: "The server is identifying, hashing, and inspecting this file.",
    activeRequest: "This status reflects the active server request. No simulated percentage is shown.",
    cancel: "Cancel",
    releaseInspect: "Release to inspect",
    images: "Images",
    documents: "Documents",
    video: "Video",
    audio: "Audio",
    archives: "Archives",
    binaries: "Binaries",
    exportReport: "Export report",
    analysisComplete: "Analysis complete",
    analyzeAnother: "Analyze another",
    clearMetadata: "Clear metadata",
    clearingMetadata: "Clearing metadata…",
    fileFingerprints: "File fingerprints",
    privacyAnalysis: "Privacy analysis",
    forensicTimeline: "Forensic timeline",
    metadataExplorer: "Metadata explorer",
    fileStructure: "File structure",
    printableStrings: "Printable strings",
    hexViewer: "Hex viewer",
    noFindings: "No findings were reported for this section.",
    addMoreFiles: "Add more files",
    dropFiles: "Drop files here",
    chooseMultiple: "or click to choose multiple files",
    clear: "Clear",
    analyzeQueued: "Analyze",
    files: "files",
    uploadQueue: "Upload queue",
    batchResults: "Batch results",
    searchFilenames: "Search filenames…",
    allFiles: "All files",
    withFindings: "With findings",
    withLocation: "With location",
    highPrivacy: "High privacy",
    noMatch: "No analyzed files match this view.",
    fileA: "File A",
    fileB: "File B",
    chooseFile: "Choose",
    replace: "Replace",
    dropOrChoose: "Drop one file or click to choose",
    inspectFull: "Inspect full result",
    metadataComparison: "Metadata comparison",
    fieldDifference: "Field-level difference",
    searchCompared: "Search compared fields…",
    compareMetadata: "Compare metadata",
    compareExplanation: "Both files are analyzed with the same engine before values are compared.",
    noDifferenceMatch: "No metadata fields match the selected difference types.",
    formatsEyebrow: "Capability registry",
    formatsTitle: "Support you can verify.",
    formatsDescription: "This page reads the active engine registry so its claims stay aligned with the parsers actually installed on this DolosMeta instance.",
    engineEyebrow: "Native inspection engine",
    engineTitle: "The file structure is the source.",
    engineDescription: "DolosMeta does not call or wrap the ExifTool executable. Its registered parsers inspect supported containers, metadata blocks, binary tags, and textual properties directly.",
    privacyEyebrow: "Privacy boundary",
    privacyTitle: "Your file stays inside this instance.",
    privacyDescription: "Files are analyzed by the DolosMeta server you connect to. The interface does not claim browser-only processing and does not require an external metadata service.",
    capabilityRegistry: "Capability registry",
    supportVerify: "Support you can verify.",
    activeRegistry: "This page reads the active engine registry so its claims stay aligned with the parsers actually installed on this DolosMeta instance.",
    analysisPath: "Analysis path",
    fromUpload: "From upload to structured evidence",
    boundedDefault: "Bounded by default",
    untrustedFiles: "Built for untrusted files",
    untrustedCopy: "Parsers validate offsets and lengths, cap recursion and decompression, reject unsafe XML features, and return partial results with structured warnings when recovery is possible.",
    evidenceAwareTitle: "Observations, not verdicts",
    evidenceAwareCopy: "The interface uses language such as ‘the file reports’ because metadata can be changed. High entropy, embedded content, or inconsistent timestamps are context, not automatic malware conclusions.",
    extensibleRegistry: "Extensible registry",
    parsersIndependent: "Parsers stay independent",
    parsersCopy: "A format parser implements a common contract and returns bounded structured data. New formats can be registered without rewriting the API or user interface.",
    viewRegistry: "View the active parser registry →",
    defaultPosture: "Default posture",
    analyzeSubmitted: "Analyze only what the user submits.",
    analyzeSubmittedCopy: "No account is required for local analysis. Results are tied to the temporary analysis session rather than used for permanent user tracking.",
    noThirdParty: "No third-party analysis",
    noThirdPartyCopy: "Uploaded files are not automatically forwarded to VirusTotal, cloud AI, geocoding, OCR, or external metadata services.",
    noConnections: "No automatic connections",
    noConnectionsCopy: "DolosMeta does not visit URLs, resolve domains, load remote email images, or request map tiles discovered in a file.",
    temporaryHandling: "Temporary handling",
    temporaryCopy: "The DolosMeta server uses temporary upload storage or bounded in-memory processing and removes files after its configured retention window.",
    noActiveContent: "No active content",
    noActiveCopy: "Uploaded executables, macros, PDF JavaScript, launch actions, attachments, and embedded objects are inspected statically and never executed.",
    preciseLanguage: "Precise language",
    serverNotBrowser: "Server-local is not the same as browser-only.",
    serverNotBrowserCopy: "The browser sends the selected file to this DolosMeta server for analysis. When you run DolosMeta on your own machine, that server is local. If somebody hosts an instance elsewhere, that operator controls its infrastructure and retention configuration.",
    analysisPathTitle: "From upload to structured evidence",
    boundedTitle: "Built for untrusted files",
    evidenceTitle: "Observations, not verdicts",
    independentTitle: "Parsers stay independent",
    registryLink: "View the active parser registry →",
    readingRegistry: "Reading the active parser registry…",
    registryUnavailable: "Capability registry unavailable",
    startApi: "Start the DolosMeta API to see exactly what this instance supports.",
    emptyRegistry: "This server returned an empty parser registry. Generic analysis may still be available.",
    activeParsers: "Active parsers",
    registered: "registered",
    parser: "Parser",
    extensions: "Extensions",
    structure: "Structure",
    version: "Version",
    tableEvidence: "This table comes from the running DolosMeta instance. It does not advertise parsers that the server did not report.",
    batchEyebrow: "Multi-file inspection",
    batchTitle: "Analyze a set of files.",
    batchDescription: "Run the same native inspection pipeline across a collection, then filter findings and export one evidence-preserving report.",
    compareEyebrow: "Two-file comparison",
    compareTitle: "See exactly what changed.",
    compareDescription: "Analyze two files with the same engine and compare their reported metadata field by field.",
    stageIdentify: "Identify",
    stageIdentifyCopy: "Compare extension, declared MIME, magic bytes, and container signatures.",
    stageInspect: "Inspect",
    stageInspectCopy: "Use bounded readers to map binary structures without executing file content.",
    stageParse: "Parse",
    stageParseCopy: "Select every applicable native parser through an extensible registry.",
    stageNormalize: "Normalize",
    stageNormalizeCopy: "Map parser-specific tags into a stable, versioned metadata model.",
    stageAnalyze: "Analyze",
    stageAnalyzeCopy: "Report privacy exposure, anomalies, active content, and timeline observations.",
    stagePresent: "Present",
    stagePresentCopy: "Return structured results to the web UI, CLI, and export layer.",
  },
  ka: {
    analyze: "ანალიზი",
    batch: "ჯგუფური",
    compare: "შედარება",
    formats: "ფორმატები",
    engine: "ძრავა",
    privacy: "კონფიდენციალურობა",
    analysisModes: "ანალიზის რეჟიმები",
    productInformation: "პროდუქტის ინფორმაცია",
    localFirst: "ლოკალური რეჟიმი",
    home: "DolosMeta-ს მთავარი გვერდი",
    skipToMain: "მთავარ შინაარსზე გადასვლა",
    menu: "მენიუ",
    mobileNavigation: "მობილური ნავიგაცია",
    footerNote: "მეტამონაცემები შეიძლება შეიცვალოს. მიგნებები დაკვირვებაა და არა მტკიცებულება.",
    handled: "როგორ მუშავდება ფაილები",
    language: "ენა",
    theme: "თემა",
    dark: "მუქი",
    light: "ნათელი",
    contrast: "მაღალი კონტრასტი",
    localFileIntelligence: "ფაილის ლოკალური ინტელექტი",
    entranceTitle: "ნახეთ, რას ამჟღავნებს თქვენი ფაილები.",
    entranceCopy: "DolosMeta ადგენს ფაილის სტრუქტურას, აჩვენებს ჩაშენებულ მეტამონაცემებს, ამოწმებს მდებარეობისა და შექმნის ნიშნებს და გამოკვეთს კონფიდენციალურობის რისკებს, ფაილების მესამე მხარეს გაგზავნის გარეშე.",
    capabilities: "DolosMeta-ს შესაძლებლობები",
    identify: "ამოცნობა",
    inspect: "შემოწმება",
    clean: "გასუფთავება",
    preparing: "პირადი სამუშაო სივრცის მომზადება",
    skipIntro: "შესავლის გამოტოვება",
    singleFile: "ერთი ფაილი",
    chooseWorkflow: "ანალიზის სამუშაო რეჟიმი",
    universalIntelligence: "ფაილის უნივერსალური ინტელექტი",
    heroCopy: "შეამოწმეთ დამალული მეტამონაცემები, დროის ნიშნები, გეოლოკაცია, მოწყობილობის ინფორმაცია, დოკუმენტის თვისებები და ფაილის სტრუქტურა ერთ პირად სამუშაო სივრცეში.",
    dropFile: "გადმოიტანეთ ფაილი აქ",
    clickChoose: "ან დააჭირეთ ფაილის ასარჩევად",
    retention: "ფაილები ამ DolosMeta-ს ინსტანციაში რჩება და ავტომატურად იშლება.",
    nativeParsing: "ნეიტიური ანალიზი",
    noExifTool: "ExifTool-ის გარეშე",
    privateByDesign: "კონფიდენციალურობა დიზაინით",
    noExternalUploads: "გარე სერვისებზე ატვირთვის გარეშე",
    evidenceAware: "მტკიცებულებაზე ორიენტირებული",
    observationsNotVerdicts: "დაკვირვებები და არა განაჩენები",
    analysisInterrupted: "ანალიზი შეწყდა",
    couldNotInspect: "ამ ფაილის შემოწმება ვერ მოხერხდა.",
    tryAgain: "ხელახლა ცდა",
    chooseAnother: "სხვა ფაილის არჩევა",
    analysisUnavailable: "ანალიზი მიუწვდომელია",
    savedAnalysis: "შენახული ანალიზი",
    retrieveAnalysis: "ამ DolosMeta სესიიდან ანალიზის შედეგის მიღება.",
    analysisInProgress: "ანალიზი მიმდინარეობს",
    serverInspecting: "სერვერი ადგენს, ჰეშავს და ამოწმებს ამ ფაილს.",
    activeRequest: "ეს სტატუსი ასახავს სერვერის აქტიურ მოთხოვნას. პროცენტი სიმულირებული არ არის.",
    cancel: "გაუქმება",
    releaseInspect: "გაუშვით შესამოწმებლად",
    images: "სურათები",
    documents: "დოკუმენტები",
    video: "ვიდეო",
    audio: "აუდიო",
    archives: "არქივები",
    binaries: "ბინარული ფაილები",
    exportReport: "ანგარიშის ექსპორტი",
    analysisComplete: "ანალიზი დასრულდა",
    analyzeAnother: "სხვა ფაილის ანალიზი",
    clearMetadata: "მეტამონაცემების გასუფთავება",
    clearingMetadata: "მეტამონაცემები იწმინდება…",
    fileFingerprints: "ფაილის ანაბეჭდები",
    privacyAnalysis: "კონფიდენციალურობის ანალიზი",
    forensicTimeline: "ფორენზიკული ქრონოლოგია",
    metadataExplorer: "მეტამონაცემების მიმოხილვა",
    fileStructure: "ფაილის სტრუქტურა",
    printableStrings: "ამოსაბეჭდი სტრიქონები",
    hexViewer: "ჰექს-დათვალიერება",
    noFindings: "ამ განყოფილებისთვის მიგნებები არ დაფიქსირებულა.",
    addMoreFiles: "მეტი ფაილის დამატება",
    dropFiles: "ფაილები გადმოიტანეთ აქ",
    chooseMultiple: "ან დააჭირეთ რამდენიმე ფაილის ასარჩევად",
    clear: "გასუფთავება",
    analyzeQueued: "ანალიზი",
    files: "ფაილი",
    uploadQueue: "ატვირთვის რიგი",
    batchResults: "ჯგუფური შედეგები",
    searchFilenames: "ფაილების სახელების ძიება…",
    allFiles: "ყველა ფაილი",
    withFindings: "მიგნებებით",
    withLocation: "მდებარეობით",
    highPrivacy: "მაღალი კონფიდენციალურობის რისკი",
    noMatch: "ამ ხედს შესაბამისი გაანალიზებული ფაილი არ აქვს.",
    fileA: "ფაილი A",
    fileB: "ფაილი B",
    chooseFile: "არჩევა",
    replace: "ჩანაცვლება",
    dropOrChoose: "გადმოიტანეთ ფაილი ან დააჭირეთ ასარჩევად",
    inspectFull: "სრული შედეგის ნახვა",
    metadataComparison: "მეტამონაცემების შედარება",
    fieldDifference: "ველების განსხვავება",
    searchCompared: "შედარებული ველების ძიება…",
    compareMetadata: "მეტამონაცემების შედარება",
    compareExplanation: "ორივე ფაილი ერთი და იმავე ძრავით მოწმდება, შემდეგ კი მნიშვნელობები შედარდება.",
    noDifferenceMatch: "არჩეულ განსხვავებების ტიპებს შესაბამისი ველი არ აქვს.",
    formatsEyebrow: "შესაძლებლობების რეესტრი",
    formatsTitle: "დადასტურებადი მხარდაჭერა.",
    formatsDescription: "ეს გვერდი აქტიურ ძრავის რეესტრს კითხულობს, რათა აღწერა ზუსტად ემთხვეოდეს ამ DolosMeta-ს ინსტანციაში დაყენებულ პარსერებს.",
    engineEyebrow: "ნეიტიური შემოწმების ძრავა",
    engineTitle: "ფაილის სტრუქტურა არის წყარო.",
    engineDescription: "DolosMeta არ იძახებს და არ იყენებს ExifTool-ს. მისი პარსერები უშუალოდ ამოწმებენ მხარდაჭერილ კონტეინერებს, მეტამონაცემებს, ბინარულ ტეგებსა და ტექსტურ თვისებებს.",
    privacyEyebrow: "კონფიდენციალურობის საზღვარი",
    privacyTitle: "თქვენი ფაილი ამ ინსტანციაში რჩება.",
    privacyDescription: "ფაილებს თქვენ მიერ არჩეული DolosMeta-ს სერვერი ამუშავებს. ინტერფეისი არ ამტკიცებს, რომ დამუშავება მხოლოდ ბრაუზერში ხდება და გარე მეტამონაცემების სერვისი საჭირო არ არის.",
    capabilityRegistry: "შესაძლებლობების რეესტრი",
    supportVerify: "დადასტურებადი მხარდაჭერა.",
    activeRegistry: "ეს გვერდი აქტიურ ძრავის რეესტრს კითხულობს, რათა აღწერა ზუსტად ემთხვეოდეს დაყენებულ პარსერებს.",
    analysisPath: "ანალიზის გზა",
    fromUpload: "ატვირთვიდან სტრუქტურირებულ მტკიცებულებამდე",
    boundedDefault: "შეზღუდვები ნაგულისხმევად",
    untrustedFiles: "შექმნილია არასანდო ფაილებისთვის",
    untrustedCopy: "პარსერები ამოწმებენ ოფსეტებსა და სიგრძეებს, ზღუდავენ რეკურსიასა და დეკომპრესიას, უარყოფენ სახიფათო XML-ს და აღდგენისას ნაწილობრივ შედეგებს აბრუნებენ.",
    evidenceAwareTitle: "დაკვირვებები და არა განაჩენები",
    evidenceAwareCopy: "ინტერფეისი ამბობს „ფაილი იტყობინება“, რადგან მეტამონაცემები შეიძლება შეიცვალოს. მაღალი ენტროპია ან ჩაშენებული შიგთავსი თავისთავად მავნე პროგრამას არ ნიშნავს.",
    extensibleRegistry: "გაფართოებადი რეესტრი",
    parsersIndependent: "პარსერები დამოუკიდებელია",
    parsersCopy: "ფორმატის პარსერი საერთო კონტრაქტს ასრულებს და შეზღუდულ სტრუქტურირებულ მონაცემებს აბრუნებს.",
    viewRegistry: "აქტიური პარსერების რეესტრი →",
    defaultPosture: "ნაგულისხმევი მიდგომა",
    analyzeSubmitted: "ანალიზდება მხოლოდ მომხმარებლის მიერ წარდგენილი.",
    analyzeSubmittedCopy: "ლოკალური ანალიზისთვის ანგარიში საჭირო არ არის. შედეგები დროებით სესიას უკავშირდება და მუდმივი თვალთვალისთვის არ გამოიყენება.",
    noThirdParty: "მესამე მხარის ანალიზის გარეშე",
    noThirdPartyCopy: "ატვირთული ფაილები ავტომატურად არ იგზავნება გარე ანალიზის, OCR-ის, გეოკოდირების ან ღრუბლოვანი AI-ს სერვისებში.",
    noConnections: "ავტომატური კავშირების გარეშე",
    noConnectionsCopy: "DolosMeta არ სტუმრობს URL-ებს, არ ხსნის დომენებს და არ ითხოვს ფაილში აღმოჩენილ რუკის ფილებს.",
    temporaryHandling: "დროებითი დამუშავება",
    temporaryCopy: "სერვერი დროებით საცავს ან შეზღუდულ მეხსიერებას იყენებს და ფაილებს შენახვის ვადის შემდეგ შლის.",
    noActiveContent: "აქტიური შიგთავსის გარეშე",
    noActiveCopy: "შესრულებადი ფაილები, მაკროები, PDF JavaScript და ჩაშენებული ობიექტები მხოლოდ სტატიკურად მოწმდება და არ ეშვება.",
    preciseLanguage: "ზუსტი ენა",
    serverNotBrowser: "სერვერზე ლოკალური არ ნიშნავს მხოლოდ ბრაუზერში.",
    serverNotBrowserCopy: "ბრაუზერი არჩეულ ფაილს ანალიზისთვის ამ DolosMeta-ს სერვერს უგზავნის. საკუთარ მოწყობილობაზე გაშვებისას სერვერი ლოკალურია.",
    analysisPathTitle: "ატვირთვიდან სტრუქტურირებულ მტკიცებულებამდე",
    boundedTitle: "შექმნილია არასანდო ფაილებისთვის",
    evidenceTitle: "დაკვირვებები და არა განაჩენები",
    independentTitle: "პარსერები დამოუკიდებელია",
    registryLink: "აქტიური პარსერების რეესტრი →",
    readingRegistry: "აქტიური პარსერების რეესტრის წაკითხვა…",
    registryUnavailable: "შესაძლებლობების რეესტრი მიუწვდომელია",
    startApi: "ჩართეთ DolosMeta-ს API ამ ინსტანციის შესაძლებლობების სანახავად.",
    emptyRegistry: "სერვერმა ცარიელი რეესტრი დააბრუნა. ზოგადი ანალიზი მაინც შეიძლება იყოს ხელმისაწვდომი.",
    activeParsers: "აქტიური პარსერები",
    registered: "რეგისტრირებული",
    parser: "პარსერი",
    extensions: "გაფართოებები",
    structure: "სტრუქტურა",
    version: "ვერსია",
    tableEvidence: "ეს ცხრილი გაშვებული DolosMeta-ს ინსტანციიდან მოდის და მხოლოდ სერვერის მიერ დადასტურებულ პარსერებს აჩვენებს.",
    batchEyebrow: "მრავალი ფაილის შემოწმება",
    batchTitle: "გაანალიზეთ ფაილების ნაკრები.",
    batchDescription: "ერთი და იგივე ნეიტიური შემოწმება გაუშვით კოლექციაზე, შემდეგ გაფილტრეთ მიგნებები და გაიტანეთ ანგარიში.",
    compareEyebrow: "ორი ფაილის შედარება",
    compareTitle: "ზუსტად ნახეთ, რა შეიცვალა.",
    compareDescription: "ორი ფაილი ერთი და იგივე ძრავით შეამოწმეთ და მეტამონაცემები ველების მიხედვით შეადარეთ.",
    stageIdentify: "ამოცნობა",
    stageIdentifyCopy: "შეადარეთ გაფართოება, MIME, მაგიური ბაიტები და კონტეინერის ხელმოწერები.",
    stageInspect: "შემოწმება",
    stageInspectCopy: "შეზღუდული მკითხველებით შეისწავლეთ ბინარული სტრუქტურა შიგთავსის გაშვების გარეშე.",
    stageParse: "გარჩევა",
    stageParseCopy: "გაფართოებადი რეესტრიდან აირჩიეთ შესაბამისი ნეიტიური პარსერი.",
    stageNormalize: "ნორმალიზაცია",
    stageNormalizeCopy: "პარსერის სპეციფიკური ტეგები გადაიყვანეთ სტაბილურ, ვერსირებულ მოდელში.",
    stageAnalyze: "ანალიზი",
    stageAnalyzeCopy: "აჩვენეთ კონფიდენციალურობის რისკები, ანომალიები, აქტიური შიგთავსი და ქრონოლოგია.",
    stagePresent: "წარდგენა",
    stagePresentCopy: "სტრუქტურირებული შედეგები დააბრუნეთ ვებსაიტში, CLI-სა და ექსპორტში.",
  },
  ru: {
    analyze: "Анализ",
    batch: "Пакетный анализ",
    compare: "Сравнение",
    formats: "Форматы",
    engine: "Движок",
    privacy: "Приватность",
    analysisModes: "Режимы анализа",
    productInformation: "Информация о продукте",
    localFirst: "Локальная обработка",
    home: "Главная DolosMeta",
    skipToMain: "Перейти к основному содержимому",
    menu: "Меню",
    mobileNavigation: "Мобильная навигация",
    footerNote: "Метаданные можно изменить. Результаты анализа — наблюдения, а не доказательства.",
    handled: "Как обрабатываются файлы",
    language: "Язык",
    theme: "Тема",
    dark: "Тёмная",
    light: "Светлая",
    contrast: "Высокий контраст",
    localFileIntelligence: "Локальный анализ файлов",
    entranceTitle: "Узнайте, что раскрывают ваши файлы.",
    entranceCopy: "DolosMeta определяет структуру файла, показывает встроенные метаданные, отслеживает признаки местоположения и создания и отмечает риски приватности, не отправляя файлы третьим сторонам.",
    capabilities: "Возможности DolosMeta",
    identify: "Определить",
    inspect: "Проверить",
    clean: "Очистить",
    preparing: "Подготовка приватного рабочего пространства",
    skipIntro: "Пропустить вступление",
    singleFile: "Один файл",
    chooseWorkflow: "Выбор режима анализа",
    universalIntelligence: "Универсальный анализ файлов",
    heroCopy: "Проверяйте скрытые метаданные, временные метки, геолокацию, сведения об устройстве, свойства документов и структуру файла в одном приватном рабочем пространстве.",
    dropFile: "Перетащите файл сюда",
    clickChoose: "или нажмите, чтобы выбрать файл",
    retention: "Файлы остаются в этом экземпляре DolosMeta и удаляются автоматически.",
    nativeParsing: "Нативный анализ",
    noExifTool: "Без зависимости от ExifTool",
    privateByDesign: "Приватность по умолчанию",
    noExternalUploads: "Без внешней загрузки файлов",
    evidenceAware: "Ориентация на факты",
    observationsNotVerdicts: "Наблюдения, а не вердикты",
    analysisInterrupted: "Анализ прерван",
    couldNotInspect: "Не удалось проверить этот файл.",
    tryAgain: "Повторить",
    chooseAnother: "Выбрать другой файл",
    analysisUnavailable: "Анализ недоступен",
    savedAnalysis: "Сохранённый анализ",
    retrieveAnalysis: "Получение результата анализа из этой сессии DolosMeta.",
    analysisInProgress: "Анализ выполняется",
    serverInspecting: "Сервер определяет формат, создаёт хэши и проверяет этот файл.",
    activeRequest: "Этот статус отражает активный запрос к серверу. Проценты не симулируются.",
    cancel: "Отмена",
    releaseInspect: "Отпустите для проверки",
    images: "Изображения",
    documents: "Документы",
    video: "Видео",
    audio: "Аудио",
    archives: "Архивы",
    binaries: "Бинарные файлы",
    exportReport: "Экспорт отчёта",
    analysisComplete: "Анализ завершён",
    analyzeAnother: "Анализировать другой файл",
    clearMetadata: "Очистить метаданные",
    clearingMetadata: "Метаданные очищаются…",
    fileFingerprints: "Отпечатки файла",
    privacyAnalysis: "Анализ приватности",
    forensicTimeline: "Криминалистическая хронология",
    metadataExplorer: "Обзор метаданных",
    fileStructure: "Структура файла",
    printableStrings: "Печатные строки",
    hexViewer: "Просмотр HEX",
    noFindings: "Для этого раздела результаты не обнаружены.",
    addMoreFiles: "Добавить файлы",
    dropFiles: "Перетащите файлы сюда",
    chooseMultiple: "или нажмите, чтобы выбрать несколько файлов",
    clear: "Очистить",
    analyzeQueued: "Анализировать",
    files: "файлов",
    uploadQueue: "Очередь загрузки",
    batchResults: "Пакетные результаты",
    searchFilenames: "Поиск по именам файлов…",
    allFiles: "Все файлы",
    withFindings: "С результатами",
    withLocation: "С местоположением",
    highPrivacy: "Высокий риск приватности",
    noMatch: "Нет проанализированных файлов, соответствующих этому виду.",
    fileA: "Файл A",
    fileB: "Файл B",
    chooseFile: "Выбрать",
    replace: "Заменить",
    dropOrChoose: "Перетащите файл или нажмите, чтобы выбрать",
    inspectFull: "Открыть полный результат",
    metadataComparison: "Сравнение метаданных",
    fieldDifference: "Различия по полям",
    searchCompared: "Поиск среди сравненных полей…",
    compareMetadata: "Сравнить метаданные",
    compareExplanation: "Оба файла анализируются одним движком, после чего значения сравниваются.",
    noDifferenceMatch: "Нет полей метаданных для выбранных типов различий.",
    formatsEyebrow: "Реестр возможностей",
    formatsTitle: "Поддержка, которую можно проверить.",
    formatsDescription: "Эта страница читает активный реестр движка, поэтому описание соответствует установленным парсерам DolosMeta.",
    engineEyebrow: "Нативный движок анализа",
    engineTitle: "Источник — структура файла.",
    engineDescription: "DolosMeta не вызывает и не оборачивает ExifTool. Зарегистрированные парсеры напрямую проверяют контейнеры, блоки метаданных, бинарные теги и текстовые свойства.",
    privacyEyebrow: "Граница приватности",
    privacyTitle: "Ваш файл остаётся в этом экземпляре.",
    privacyDescription: "Файлы анализирует подключённый вами сервер DolosMeta. Интерфейс не заявляет о работе только в браузере и не требует внешнего сервиса метаданных.",
    capabilityRegistry: "Реестр возможностей",
    supportVerify: "Поддержка, которую можно проверить.",
    activeRegistry: "Эта страница читает активный реестр движка и показывает реально установленные парсеры.",
    analysisPath: "Путь анализа",
    fromUpload: "От загрузки к структурированным свидетельствам",
    boundedDefault: "Ограничения по умолчанию",
    untrustedFiles: "Для недоверенных файлов",
    untrustedCopy: "Парсеры проверяют смещения и длины, ограничивают рекурсию и распаковку, отклоняют опасный XML и возвращают частичные результаты с предупреждениями.",
    evidenceAwareTitle: "Наблюдения, а не вердикты",
    evidenceAwareCopy: "Интерфейс говорит «файл сообщает», поскольку метаданные можно изменить. Энтропия и встроенное содержимое сами по себе не доказывают наличие вредоносной программы.",
    extensibleRegistry: "Расширяемый реестр",
    parsersIndependent: "Парсеры независимы",
    parsersCopy: "Парсер формата реализует общий контракт и возвращает ограниченные структурированные данные.",
    viewRegistry: "Открыть реестр парсеров →",
    defaultPosture: "Принцип по умолчанию",
    analyzeSubmitted: "Анализируется только отправленное пользователем.",
    analyzeSubmittedCopy: "Для локального анализа аккаунт не нужен. Результаты привязаны к временной сессии, а не к постоянному отслеживанию.",
    noThirdParty: "Без анализа третьими сторонами",
    noThirdPartyCopy: "Файлы не пересылаются автоматически в VirusTotal, облачный AI, OCR, геокодирование или внешние сервисы метаданных.",
    noConnections: "Без автоматических подключений",
    noConnectionsCopy: "DolosMeta не открывает URL, не разрешает домены и не запрашивает карты, найденные в файле.",
    temporaryHandling: "Временная обработка",
    temporaryCopy: "Сервер использует временное хранилище и удаляет файлы после заданного срока хранения.",
    noActiveContent: "Без активного содержимого",
    noActiveCopy: "Исполняемые файлы, макросы, JavaScript в PDF и вложенные объекты проверяются статически и не запускаются.",
    preciseLanguage: "Точная формулировка",
    serverNotBrowser: "Локальный сервер — не то же самое, что только браузер.",
    serverNotBrowserCopy: "Браузер отправляет выбранный файл на этот сервер DolosMeta для анализа. При запуске на своём компьютере сервер является локальным.",
    analysisPathTitle: "От загрузки к структурированным свидетельствам",
    boundedTitle: "Для недоверенных файлов",
    evidenceTitle: "Наблюдения, а не вердикты",
    independentTitle: "Парсеры независимы",
    registryLink: "Открыть реестр парсеров →",
    readingRegistry: "Чтение активного реестра парсеров…",
    registryUnavailable: "Реестр возможностей недоступен",
    startApi: "Запустите API DolosMeta, чтобы увидеть возможности этого экземпляра.",
    emptyRegistry: "Сервер вернул пустой реестр. Общий анализ всё ещё может быть доступен.",
    activeParsers: "Активные парсеры",
    registered: "зарегистрировано",
    parser: "Парсер",
    extensions: "Расширения",
    structure: "Структура",
    version: "Версия",
    tableEvidence: "Эта таблица получена от работающего экземпляра DolosMeta и показывает только заявленные сервером парсеры.",
    batchEyebrow: "Анализ нескольких файлов",
    batchTitle: "Анализируйте набор файлов.",
    batchDescription: "Запустите один нативный конвейер для коллекции, отфильтруйте результаты и экспортируйте единый отчёт.",
    compareEyebrow: "Сравнение двух файлов",
    compareTitle: "Узнайте, что изменилось.",
    compareDescription: "Проанализируйте два файла одним движком и сравните их метаданные по каждому полю.",
    stageIdentify: "Определить",
    stageIdentifyCopy: "Сравнить расширение, MIME, сигнатуру байтов и подписи контейнера.",
    stageInspect: "Проверить",
    stageInspectCopy: "Изучить бинарную структуру ограниченными чтениями без запуска содержимого.",
    stageParse: "Разобрать",
    stageParseCopy: "Выбрать подходящий нативный парсер через расширяемый реестр.",
    stageNormalize: "Нормализовать",
    stageNormalizeCopy: "Преобразовать теги парсера в стабильную версионированную модель метаданных.",
    stageAnalyze: "Проанализировать",
    stageAnalyzeCopy: "Показать риски приватности, аномалии, активное содержимое и события хронологии.",
    stagePresent: "Представить",
    stagePresentCopy: "Вернуть структурированные результаты в веб-интерфейс, CLI и экспорт.",
  },
};

interface PreferencesValue {
  language: Language;
  theme: Theme;
  setLanguage: (language: Language) => void;
  setTheme: (theme: Theme) => void;
  t: (key: string) => string;
}

const fallbackPreferences: PreferencesValue = {
  language: "en",
  theme: "dark",
  setLanguage: () => undefined,
  setTheme: () => undefined,
  t: (key) => translations.en[key] ?? key,
};

const PreferencesContext = createContext<PreferencesValue>(fallbackPreferences);

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const [theme, setTheme] = useState<Theme>("dark");

  useEffect(() => {
    const hydrateTimer = window.setTimeout(() => {
      const savedLanguage = window.localStorage.getItem("dolosmeta-language") as Language | null;
      const savedTheme = window.localStorage.getItem("dolosmeta-theme") as Theme | null;
      if (savedLanguage && savedLanguage in translations) setLanguage(savedLanguage);
      if (savedTheme && ["dark", "light", "contrast"].includes(savedTheme)) setTheme(savedTheme);
    }, 0);
    return () => window.clearTimeout(hydrateTimer);
  }, []);

  useEffect(() => {
    window.localStorage.setItem("dolosmeta-language", language);
    document.documentElement.lang = language === "ka" ? "ka" : language;
  }, [language]);

  useEffect(() => {
    window.localStorage.setItem("dolosmeta-theme", theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const value = useMemo(
    () => ({ language, theme, setLanguage, setTheme, t: (key: string) => translations[language][key] ?? translations.en[key] ?? key }),
    [language, theme],
  );
  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences(): PreferencesValue {
  const value = useContext(PreferencesContext);
  return value;
}

export function Translated({ id }: { id: string }) {
  const { t } = usePreferences();
  return <>{t(id)}</>;
}